// Copyright © Advanced Micro Devices, Inc., or its affiliates.
//
// SPDX-License-Identifier: MIT

//! Regenerate (or verify) the Cargo dependency table in MANIFEST.md from
//! `cargo metadata`, so the published manifest of third-party crates stays in
//! sync with the lockfile.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};
use serde::Deserialize;

use crate::paths;

/// Marker comments bracketing the generated dependency table in MANIFEST.md.
const MANIFEST_BEGIN: &str =
    "<!-- BEGIN CARGO DEPENDENCIES (generated by `cargo xtask manifest`; do not edit by hand) -->";
const MANIFEST_END: &str = "<!-- END CARGO DEPENDENCIES -->";

/// Subset of the `cargo metadata` JSON output we care about.
#[derive(Deserialize)]
struct Metadata {
    workspace_root: String,
    packages: Vec<Package>,
}

/// Subset of a single package entry from `cargo metadata`.
#[derive(Deserialize)]
struct Package {
    name: String,
    version: String,
    /// `None` for workspace members; `Some(_)` for external (registry/git) deps.
    source: Option<String>,
    /// `None` when the crate declares no SPDX license expression.
    license: Option<String>,
}

/// Run `cargo metadata` and deserialize the parts we need.
///
/// Always passes `--locked` so both write and check modes use the committed
/// `Cargo.lock` exactly, keeping them consistent and preventing CI from
/// resolving to newer registry versions mid-run.
fn load_metadata() -> Result<Metadata> {
    let stdout = paths::run_cargo_metadata(&[])?;
    serde_json::from_slice(&stdout).context("failed to parse `cargo metadata` output")
}

/// Build the markdown dependency table (header, separator, and one row per
/// external dependency, sorted ascending by name then version).
fn render_dependency_table(metadata: &Metadata) -> String {
    use std::fmt::Write as _;

    let mut rows: Vec<(&str, &str, &str)> = metadata
        .packages
        .iter()
        .filter(|pkg| pkg.source.is_some())
        .map(|pkg| {
            (
                pkg.name.as_str(),
                pkg.version.as_str(),
                pkg.license.as_deref().unwrap_or("UNKNOWN"),
            )
        })
        .collect();
    // Sort by name, then by semantic version. A plain string sort would order
    // versions lexicographically (e.g. `0.10.1` before `0.9.4`), which is wrong;
    // compare parsed semver instead. Versions from `cargo metadata` are always
    // valid semver, but fall back to string order if parsing ever fails so the
    // output stays deterministic.
    rows.sort_unstable_by(|a, b| {
        a.0.cmp(b.0).then_with(|| {
            match (semver::Version::parse(a.1), semver::Version::parse(b.1)) {
                (Ok(va), Ok(vb)) => va.cmp(&vb),
                _ => a.1.cmp(b.1),
            }
        })
    });

    let mut table = String::from("| Crate | Version | License |\n|-------|---------|---------|\n");
    for (name, version, license) in rows {
        // Writing to a String is infallible.
        let _ = writeln!(table, "| {name} | {version} | {license} |");
    }
    table
}

/// Replace the content between the BEGIN/END markers with `table`, preserving
/// the markers themselves and the surrounding document.
fn splice_table(manifest: &str, table: &str) -> Result<String> {
    let begin = manifest
        .find(MANIFEST_BEGIN)
        .with_context(|| format!("MANIFEST.md is missing the marker `{MANIFEST_BEGIN}`"))?;
    // Search for END starting after BEGIN so an earlier occurrence of the marker
    // text (e.g. in an example or future section) doesn't splice the wrong region.
    let end = manifest[begin + MANIFEST_BEGIN.len()..]
        .find(MANIFEST_END)
        .map(|offset| begin + MANIFEST_BEGIN.len() + offset)
        .with_context(|| format!("MANIFEST.md is missing the marker `{MANIFEST_END}`"))?;
    // `table` already ends with a newline, so the END marker lands on its own line.
    let before = &manifest[..begin + MANIFEST_BEGIN.len()];
    let after = &manifest[end + MANIFEST_END.len()..];
    Ok(format!("{before}\n{table}{MANIFEST_END}{after}"))
}

/// Regenerate (or, with `check`, verify) the dependency table in MANIFEST.md.
pub fn run(check: bool) -> Result<()> {
    let metadata = load_metadata()?;
    let manifest_path = Path::new(&metadata.workspace_root).join("MANIFEST.md");
    let current = fs::read_to_string(&manifest_path)
        .with_context(|| format!("failed to read {}", manifest_path.display()))?;
    let table = render_dependency_table(&metadata);
    let updated = splice_table(&current, &table)?;

    if check {
        if updated != current {
            bail!(
                "MANIFEST.md dependency table is out of date; run `cargo xtask manifest` to update it"
            );
        }
        return Ok(());
    }

    if updated != current {
        fs::write(&manifest_path, updated)
            .with_context(|| format!("failed to write {}", manifest_path.display()))?;
    }
    Ok(())
}
